---
# tasks file for vagrant7

# deltarpmのインストール
- name: install_deltarpm
  yum:
    name: deltarpm
    state: present

# 秘伝のたれ
- name: install_puppetlabs-release
  yum: 
    name: https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
    state: present
