---
# tasks file for python-scripts
- name: install python
  yum:
    name:
      - python3
      - python-devel
      - jq

- name: install gspread oauth2client
  shell: pip3 install gspread oauth2client

- name: put script
  template:
    src: ../templates/{{ item }}
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755
    backup: yes
  with_items:
    - main.py
    - main2.py
    - main3.py

- name: put scret-key
  template:
    src: ../templates/sacred-drive.json
    dest: /usr/local/jmeter/bin/
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: put start script
  template:
    src: ../templates/{{ item }}
    dest: /usr/local/jmeter/bin/
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - start-controller_cui.sh
    - start-controller_cui2.sh
    - start-controller_cui3.sh
